package com.survey.geneza.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * AnswerOptionTemplate Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "AnswerOptionTemplate")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "SurveyRest/com/survey/geneza/domain", name = "AnswerOptionTemplate")
public class AnswerOptionTemplate implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    

    @Column(name = "answerOptionTemplate")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String answerOptionTemplate;
    


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public String getAnswerOptionTemplate() {
        return answerOptionTemplate;
    }
    
    public void setAnswerOptionTemplate(String answerOptionTemplate) {
        this.answerOptionTemplate = answerOptionTemplate;
    }


    public AnswerOptionTemplate() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof AnswerOptionTemplate))
            return false;
        AnswerOptionTemplate equalCheck = (AnswerOptionTemplate) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}