package com.survey.geneza.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * AnswerOption Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "AnswerOption")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "SurveyRest/com/survey/geneza/domain", name = "AnswerOption")
public class AnswerOption implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    @Column(name = "optionValue")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String optionValue;@Column(name = "sequence")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer sequence;
    @ManyToOne
    @JoinColumn(name="question")
    private Question question;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Question getQuestion() {
        return question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    
    public String getOptionValue() {
        return optionValue;
    }
    
    public void setOptionValue(String optionValue) {
        this.optionValue = optionValue;
    }
    
    public Integer getSequence() {
        return sequence;
    }
    
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }


    public AnswerOption() {
    }

    public AnswerOption(Integer id) {
    this.id = id;
    }

    


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof AnswerOption))
            return false;
        AnswerOption equalCheck = (AnswerOption) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}