package com.survey.geneza.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import javax.persistence.Id;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * Question Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "Question")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "SurveyRest/com/survey/geneza/domain", name = "Question")
public class Question implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    @Column(name = "section")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String section;@Column(name = "childOrder")
    @Basic(fetch = FetchType.EAGER)
     @XmlElement
    private Integer childOrder;@Column(name = "surveyOrder")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private Integer surveyOrder;
    @ManyToOne
    @JoinColumn(name="surveyId")
    private Survey survey;@ManyToOne
    @JoinColumn(name="questionType")
    private QuestionType questionType;@ManyToOne
    @JoinColumn(name="parentQuestion")
    private Question parentQuestion;
    @Column(name = "text") // Corrected column definition
    private String text; 



    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Survey getSurvey() {
        return survey;
    }
    
    public void setSurvey(Survey survey) {
        this.survey = survey;
    }
    
    public String getSection() {
        return section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }

    public String getText() {
        return text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    
    public QuestionType getQuestionType() {
        return questionType;
    }
    
    public void setQuestionType(QuestionType questionType) {
        this.questionType = questionType;
    }
    
    public Integer getChildOrder() {
        return childOrder;
    }
    
    public void setChildOrder(Integer childOrder) {
        this.childOrder = childOrder;
    }
    
    public Integer getSurveyOrder() {
        return surveyOrder;
    }
    
    public void setSurveyOrder(Integer surveyOrder) {
        this.surveyOrder = surveyOrder;
    }
    
    public Question getParentQuestion() {
        return parentQuestion;
    }
    
    public void setParentQuestion(Question parentQuestion) {
        this.parentQuestion = parentQuestion;
    }


    public Question() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof Question))
            return false;
        Question equalCheck = (Question) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}