package com.survey.geneza.domain;
import java.io.Serializable;
import java.lang.StringBuilder;
import java.util.Calendar;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.Date;
import java.math.*;
import javax.xml.bind.annotation.*;
import javax.persistence.*;

/**
 * ResponseAnswers Entity
 * 
 * Generated by Dunamis App Generator
 */

@Entity
@Table(name = "ResponseAnswers")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(namespace = "SurveyRest/com/survey/geneza/domain", name = "ResponseAnswers")
public class ResponseAnswers implements Serializable {
    private static final long serialVersionUID = 1L;


    @Column(name = "id")
    @Basic(fetch = FetchType.EAGER)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @XmlElement
    private Integer id;  
    @Column(name = "answerText")
    @Basic(fetch = FetchType.EAGER)
    @XmlElement
    private String answerText;
    @Column(name = "multipleAnswerOptions")
    private String multipleAnswerOptions;
    @ManyToOne
    @JoinColumn(name="question")
    private Question question;@ManyToOne
    @JoinColumn(name="answerOption")
    private AnswerOption answerOption;@ManyToOne
    @JoinColumn(name="response")
    private Response response;


    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

        
    public Question getQuestion() {
        return question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    
    public AnswerOption getAnswerOption() {
        return answerOption;
    }
    
    public void setAnswerOption(AnswerOption answerOption) {
        this.answerOption = answerOption;
    }
    
    public Response getResponse() {
        return response;
    }
    
    public void setResponse(Response response) {
        this.response = response;
    }
    
    public String getAnswerText() {
        return answerText;
    }
    
    public void setAnswerText(String answerText) {
        this.answerText = answerText;
    }

    public String getMultipleAnswerOptions() { return multipleAnswerOptions; }
    public void setMultipleAnswerOptions(String multipleAnswerOptions) { this.multipleAnswerOptions = multipleAnswerOptions; }


    public ResponseAnswers() {
    }


    public String toString() {
        StringBuilder buffer = new StringBuilder();
        buffer.append("id=[").append(id).append("] ");
        return buffer.toString();
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (int) (prime * result + ((id == null) ? 0 : id.hashCode()));
        return result;
    }


    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof ResponseAnswers))
            return false;
        ResponseAnswers equalCheck = (ResponseAnswers) obj;
        if ((id == null && equalCheck.id != null) || (id != null && equalCheck.id == null))
            return false;
        if (id != null && !id.equals(equalCheck.id))
            return false;
        return true;
    }

}